### ISSUE TITLE
rclone config should be provided as a Secret

### ISSUE THREAD

**Issue by wlritchi** [itzg/minecraft-server-charts#100]
An rclone config file contains data that should be kept secret, such as API keys for storage backends. Currently, the supported way to set the rclone config file contents is to put these contents into the values for a release. The contents will then be stored in a ConfigMap, which is not a secure place to put secrets.

It's currently possible to override this behaviour with a safer approach, if you set up the volume mounts using `extraVolumes` and create the secret manually. Here's what I'm using:
```
    extraVolumes:
      - volumeMounts:
        - name: real-rclone-config
          mountPath: /config/rclone
        volumes
        - name: real-rclone-config
          secret:
            secretName: my-rclone-config-secret
```

However, it's probably not a good idea for the chart/documentation to be encouraging users to use an unsafe configuration. The ConfigMap-based approach should be deprecated or transparently replaced with a Secret-based approach. This chart should also allow users to specify an existing secret, similarly to how the RCON password is handled; this is especially useful for GitOps-style workflows (e.g. Flux) where secrets have to be created separately from Helm release inputs.
