### ISSUE TITLE
`pruneBackupsDays` not honoured

### ISSUE THREAD

**Issue by wlritchi** [itzg/minecraft-server-charts#108]
The `minecraft` chart accepts a parameter `mcbackup.pruneBackupsDays`. However, as can be seen from [this code search](https://github.com/itzg/minecraft-server-charts/search?q=prunebackupsdays), it doesn't actually map that to the `PRUNE_BACKUPS_DAYS` env var for the mc-backup container.

As a workaround, users can pass the env var manually:
```
spec:
  values:
    extraEnv:
      PRUNE_BACKUPS_DAYS: "0"  # disable backup pruning
```
