### ISSUE TITLE
Expand port 25565 UPD - PlasmoVoice

### ISSUE THREAD

**Issue by Shagrat2** [itzg/minecraft-server-charts#137]
Hello i'am try expand port 25565 UPD for plasmoVoice

==============
```
minecraftServer:
  eula: true
  onlineMode: false
  #whitelist: shagrat2, Boris, Tonya
  ops: shagrat2
  motd: "MC Server 1.7-1.19.2"
  type: PAPER

  memory: 2048M

  spigetResources:
    - 19362 # https://www.spigotmc.org/resources/loginsecurity.19362/

    # Via - https://jo0001.github.io/ViaSetup/?lang=en
    - 19254 # https://www.spigotmc.org/resources/viaversion.19254/
    - 27448 # https://www.spigotmc.org/resources/viabackwards.27448/
    - 52109 # https://www.spigotmc.org/resources/viarewind.52109/

    - 91064 # https://www.spigotmc.org/resources/plasmo-voice-server.91064/    

  downloadModpackUrl: "https://xxx.ru/wp-content/mcplugins/plugins.zip"
    #"https://github.com/EssentialsX/Essentials/releases/download/2.19.7/EssentialsX-2.19.7.jar"
    #- 9089  # https://www.spigotmc.org/resources/essentialsx.9089/    
    #- 105128 # https://www.spigotmc.org/resources/mapmodcompanion.105128/

  rcon:
    enabled: true    
    password: "---"

  extraPorts:
    - name: voice
      containerPort: 25565
      protocol: UDP
      service:
        enabled: true
        type: LoadBalancer
        port: 25565
      ingress:
        enabled: false        

  serviceType: LoadBalancer

  overrideServerProperties: true
```

Bat port not expand.
Endpoint is empty

```
Name:         minecraft-minecraft-voice
Namespace:    minecraft
Labels:       app=minecraft-minecraft-voice
              app.kubernetes.io/managed-by=Helm
              chart=minecraft-4.4.0
              heritage=Helm
              release=minecraft
Annotations:  <none>
Subsets:
Events:  <none>
```

```
kubectl describe pod minecraft-minecraft-c4fc64977-fsfch -n minecraft 
Name:             minecraft-minecraft-c4fc64977-fsfch
Namespace:        minecraft
Priority:         0
Service Account:  default
Node:             h1/10.9.1.8
Start Time:       Sat, 12 Nov 2022 15:35:50 +0300
Labels:           app=minecraft-minecraft
                  pod-template-hash=c4fc64977
Annotations:      kubectl.kubernetes.io/restartedAt: 2022-11-06T20:38:38Z
Status:           Running
IP:               10.42.0.126
IPs:
  IP:           10.42.0.126
Controlled By:  ReplicaSet/minecraft-minecraft-c4fc64977
Containers:
  minecraft-minecraft-mc-backup:
    Container ID:   containerd://8bf80b13be6aee04d96cb35633f57f09c85a73a7db4a694149837bb1da27aa11
    Image:          itzg/mc-backup:latest
    Image ID:       docker.io/itzg/mc-backup@sha256:738f1bbe428ba7dee97b4b5d2c3c8e6534e6341d8d8577bb10e1d74a90a70a96
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sat, 12 Nov 2022 15:35:52 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     500m
      memory:  512Mi
    Environment:
      SRC_DIR:              /data
      BACKUP_NAME:          world
      INITIAL_DELAY:        2m
      BACKUP_INTERVAL:      24h
      PRUNE_BACKUPS_DAYS:   7
      PAUSE_IF_NO_PLAYERS:  true
      SERVER_PORT:          25565
      RCON_HOST:            localhost
      RCON_PORT:            25575
      RCON_PASSWORD:        <set to the key 'rcon-password' in secret 'minecraft-minecraft'>  Optional: false
      RCON_RETRIES:         5
      RCON_RETRY_INTERVAL:  10s
      EXCLUDES:             *.jar,cache,logs
      BACKUP_METHOD:        tar
      DEST_DIR:             /backups
      LINK_LATEST:          false
      TAR_COMPRESS_METHOD:  gzip
      ZSTD_PARAMETERS:      -3 --long=25 --single-thread
    Mounts:
      /backups from backupdir (rw)
      /data from datadir (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jtwm9 (ro)
  minecraft-minecraft:
    Container ID:   containerd://b1051ebc1aea9bcc9adc9070ee419eca81665c39c53a22cd16e56ace65549415
    Image:          itzg/minecraft-server:latest
    Image ID:       docker.io/itzg/minecraft-server@sha256:6167fc26921fdeffb487a69e71ff40d769c52cb814d5b8d4798a7422763afd26
    Ports:          25565/TCP, 25575/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 12 Nov 2022 15:35:52 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      1
      memory:   1Gi
    Liveness:   exec [mc-health] delay=70s timeout=1s period=5s #success=1 #failure=20
    Readiness:  exec [mc-health] delay=70s timeout=1s period=5s #success=1 #failure=20
    Environment:
      EULA:                          true
      TYPE:                          PAPER
      PAPER_DOWNLOAD_URL:            
      VERSION:                       LATEST
      DIFFICULTY:                    easy
      WHITELIST:                     
      OPS:                           shagrat2
      ICON:                          
      MAX_PLAYERS:                   20
      MAX_WORLD_SIZE:                10000
      ALLOW_NETHER:                  true
      ANNOUNCE_PLAYER_ACHIEVEMENTS:  true
      ENABLE_COMMAND_BLOCK:          true
      FORCE_GAMEMODE:                false
      GENERATE_STRUCTURES:           true
      HARDCORE:                      false
      MAX_BUILD_HEIGHT:              256
      MAX_TICK_TIME:                 60000
      SPAWN_ANIMALS:                 true
      SPAWN_MONSTERS:                true
      SPAWN_NPCS:                    true
      SPAWN_PROTECTION:              16
      VIEW_DISTANCE:                 10
      SEED:                          
      MODE:                          survival
      MOTD:                          MC Server 1.7-1.19.2
      PVP:                           false
      LEVEL_TYPE:                    DEFAULT
      GENERATOR_SETTINGS:            
      LEVEL:                         world
      MODPACK:                       https://xxx.ru/wp-content/mcplugins/plugins.zip
      SPIGET_RESOURCES:              19362,19254,27448,52109,91064
      ONLINE_MODE:                   false
      MEMORY:                        2048M
      JVM_OPTS:                      
      JVM_XX_OPTS:                   
      OVERRIDE_SERVER_PROPERTIES:    true
      ENABLE_RCON:                   true
      RCON_PASSWORD:                 <set to the key 'rcon-password' in secret 'minecraft-minecraft'>  Optional: false
    Mounts:
      /backups from backupdir (ro)
      /data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jtwm9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  minecraft-minecraft-datadir
    ReadOnly:   false
  backupdir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  minecraft-minecraft-backupdir
    ReadOnly:   false
  kube-api-access-jtwm9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  35m   default-scheduler  Successfully assigned minecraft/minecraft-minecraft-c4fc64977-fsfch to h1
  Normal  Pulled     34m   kubelet            Container image "itzg/mc-backup:latest" already present on machine
  Normal  Created    34m   kubelet            Created container minecraft-minecraft-mc-backup
  Normal  Started    34m   kubelet            Started container minecraft-minecraft-mc-backup
  Normal  Pulled     34m   kubelet            Container image "itzg/minecraft-server:latest" already present on machine
  Normal  Created    34m   kubelet            Created container minecraft-minecraft
  Normal  Started    34m   kubelet            Started container minecraft-minecraft
```
