### ISSUE TITLE
Missing values in helm templates

### ISSUE THREAD

**Issue by zetneteork** [itzg/minecraft-server-charts#141]
In the helm chart, two values are missing, as previously added in Minecraft bedrock.
https://github.com/itzg/docker-minecraft-bedrock-server/blob/ab51be217cf5f245fcb3239466f145af3a9422ba/property-definitions.json#L112

https://github.com/itzg/docker-minecraft-bedrock-server/blob/ab51be217cf5f245fcb3239466f145af3a9422ba/property-definitions.json#L116

I did not find those two values can be easily controlled in the helm chart values. 

```yaml
  "emit-server-telemetry": {
    "env": "EMIT_SERVER_TELEMETRY",
    "allowed": ["true","false"]
  },
  "enable-lan-visibility": {
    "env": "ENABLE_LAN_VISIBILITY",
    "allowed": ["true","false"]
  }
```

I expect this feature can be added.
