### ISSUE TITLE
Helm Chart Ingress

### ISSUE THREAD

**Issue by tsimouris** [itzg/minecraft-server-charts#150]
```
# ingress-route.yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minecraft
  namespace: minecraft
spec:
  entryPoints:
    - 25565/tcp
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: svc-minecraft
          port: 25565
```

and 
```
kind: IngressRouteTCP
```
is not an option . How to proceed?

Information:
Installed via Helm on EKS on AWS behind Traefik.

**References**:
- [Traefik Documentation](https://doc.traefik.io/traefik/routing/routers/)
- [Traefik Community](https://community.traefik.io/t/connecting-to-minecraft-server-via-tcp-trhough-traefik/14146/6)
