### ISSUE TITLE
extraEnv before/after interpolation

### ISSUE THREAD

**Issue by ChipWolf** [itzg/minecraft-server-charts#152]
extraEnv vars sometimes need to be interpolated in a particular order when using variable substitution, as the dependent variables must be specified before their use in the env

**Comment by itzg** [comment]
Can you provide an example since I'm not sure how the chart can be changed to fix anything like that?

**Comment by ChipWolf** [comment]
Couple of crude examples. Bare in mind the order that env is rendered in the deployment: https://github.com/itzg/minecraft-server-charts/blob/b74f8a5d14cdb4ff3237bd2758ddc8b855d3d38f/charts/minecraft/templates/deployment.yaml#L326-L337

1) Using the pod name in the JMX options:

```yaml
extraEnv:
  POD_NAME:
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
minecraftServer:
  jvmOpts: >-
    -Dserver.name=$(POD_NAME)
```

This doesn't work as `.minecraftServer.jvmOpts` is rendered before `.extraEnv`, so the variable remains as-is. There is a workaround for this scenario:


```yaml
extraEnv:
  POD_NAME:
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  JVM_OPTS: >-
    -Dserver.name=$(POD_NAME)
```


2) Non-deterministic range issues (helm/helm#4375)

Sometimes, the range is non-deterministic, this appears to be an issue when installing or upgrading a chart with the Helm CLI as it does some kind of delta, but doesn't seem to occur when using Flux Helm.

```
extraEnv:
  MC_VERSION: "1.19.2"
  SRV_BUILD: "37"
  PAPER_DOWNLOAD_URL: "https://example.org/versions/$(MC_VERSION)/builds/$(SRV_BUILD)/downloads/server-$(MC_VERSION)-$(SRV_BUILD).jar"
```

Sometimes this is rendered in the wrong order, where it appears to be in some pseudo-alphabetic manner on an upgrade if anything in the map has changed and the dependent values are rendered after the `PAPER_DOWNLOAD_URL` in this case leaving them uninterpolated.
However, this can be monkey patched by prepending the dependent values with something like `A_` and hoping for the best.

---

Ultimately, any method to guarantee the ordering of these values by weight or something would be great, even if it's just a case of ensuring the list is alphabetised entirely.

Apparently the recommended pattern is to use `keys` and `sortAlpha` to be deterministic, then the question just becomes how do you insert `extraEnv` before or after the `minecraftServer` helper values without migrating absolutely everything into extraEnv.
