### ISSUE TITLE
subPath on volumeMounts

### ISSUE THREAD

**Issue by rzumbado** [itzg/minecraft-server-charts#169]
Hi there, is there a way to mount the /data dir using a subPath within the volumeMounts?
I want to store the data within a sub folder on my PVC like: /games/minecraft/instance1/data rather than just /data.

```
volumeMounts:
    - name: datadir
      mountPath: /data
      subPath: /games/minecraft/instance1/data
```

**Comment by itzg** [comment]
From the looks of that path I believe you're thinking of a https://kubernetes.io/docs/concepts/storage/volumes#hostpath, which is what you'll declare in the https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes part of the pod not the mount within the container.

**Comment by TheAceMan** [comment]
I am using an smb share but you should be able to accomplish similar with the existing pvc that you have. I'm using the minecraft helm chart.

```
    persistence:
      dataDir:
        enabled: true
        mountPath: /data
        existingClaim: "minecraft-smb-data-pvc"
        subPath: instance1/data
```
