### ISSUE TITLE
changing type to SPIGOT causes server to stop running. 

### ISSUE THREAD

**Issue by damienj210** [itzg/minecraft-server-charts#187]
I am trying to run the standard minecraft server helm chart, 
I choose to customize helm options before install. 
These are the items I change: 
```
eula: 'TRUE'
motd: testing Minecraft on Kubernetes!
onlineMode: false
type: SPIGOT
persistence:
  annotations: {}
  dataDir:
    Size: 10Gi
    enabled: true
    existingClaim: pvc-testminecraft
```
Watching the logs during the pod creation, everything seems to be ok and it completes with "Done" but minutes later it shuts down the server. 
I have attached my logs and yaml files.
 
[testminecraft-minecraft-857d4fd99b-mtbbm_testminecraft-minecraft.log](https://github.com/itzg/minecraft-server-charts/files/14032161/testminecraft-minecraft-857d4fd99b-mtbbm_testminecraft-minecraft.log)
[testminecraft.yaml.txt](https://github.com/itzg/minecraft-server-charts/files/14032163/testminecraft.yaml.txt)

Please let me know what I'm doing wrong. 
This only happens when I change the type to SPIGOT. 
If I make all of the other changes but leave type as VANILLA it works fine. 

Thanks.
