### ISSUE TITLE
Allow for multiple Modrinth version types

### ISSUE THREAD

**Issue by 2br-2b** [itzg/minecraft-server-charts#249]
Hello!

First off, thank you so much for this chart! I've been using it to host a minecraft server for me and my friends, and this has really helpedsimplify the process!

Right now, I am trying to host a server using Geyser and Floodgate, like in [your example](https://github.com/itzg/docker-minecraft-server/blob/master/examples/geyser/docker-compose.yml). I want to source the plugins from Modrinth as oppose to their site - I figure if GeyserMC goes rouge, I prefer to have Modrinth as a third party in between. The problem is that the releases of Floodgate are in the Release channel, but Geyser is in the Beta channel. This means that I can't install both via Modrinth:

```
  modrinth:
    allowedVersionType: ????
    optionalDependencies: true
    projects:
    - floodgate
    - geyser
```

Is there a way to specify the version type for each individual plugin?

Thank you so much for your work here!
