### ISSUE TITLE
Not providing fullNameOverride to minecraft chart is failing helm deployment

### ISSUE THREAD

**Issue by janpfischer** [itzg/minecraft-server-charts#262]
I tried to upgrade from 1.24 to 1.26. With 1.25 and https://github.com/itzg/minecraft-server-charts/issues/252 and https://github.com/itzg/minecraft-server-charts/pull/253 a feature was added to override the generated names for the resources. 

I have not specified a fullNameOverride in my values.yaml and am now getting the following error when trying to upgrade to 1.26:

```
'Helm upgrade failed for release selfhosted/minecraft with chart minecraft@4.26.1:
      template: minecraft/templates/_helpers.tpl:32:14: executing "minecraft.fullname"
      at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride'
```

**Comment by itzg** [comment]
@joryirving can you help look at this?

**Comment by joryirving** [comment]
Interesting. Can you post your values file? I can't reproduce, as it works for me without defining `fullnameOverride`

**Comment by janpfischer** [comment]
Sure. This are the values. Deployed via Flux HelmRelease resource:

```yaml
values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft-secret
    image:
      repository: itzg/minecraft-server
      tag: 2025.4.0-java21
    resources:
      limits:
        cpu: 2000m
        memory: 4000Mi
      requests:
        cpu: 200m
        memory: 2000Mi
    securityContext:
      runAsUser: ${APP_UID}
      fsGroup: ${APP_GID}
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
    startupProbe:
      enabled: true
    extraEnv:
      ENABLE_ROLLING_LOGS: true
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-data
    serviceAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      io.cilium/lb-ipam-ips: ****
      coredns.io/hostname: minecraft-server.${SECRET_DOMAIN}
    minecraftServer:
      eula: true
      version: 1.21.4
      type: PAPER
      difficulty: normal
      pvp: true
      whitelist: ****
      ops: ****
      motd: Meh
      worldSaveName: world
      viewDistance: 12
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=70"
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: map
          containerPort: 8100
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8100
          ingress:
            ingressClassName: external
            enabled: true
            hosts:
              - name: &host minecraft.${SECRET_DOMAIN}
                path: /
            tls: [hosts: [*host]]
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
```
