### ISSUE TITLE
[minecraft] allow valueFrom for extraEnv

### ISSUE THREAD

**Issue by ChipWolf** [itzg/minecraft-server-charts#71]
I have a couple of use cases that require me to inject extra environment variables which require the use of `valueFrom`.

This could be implemented into the chart by exposing an additional variable that accepts the full deployment `spec.template.spec.containers[].env` syntax. This would only require a minor release.

```yaml
someNewExtraEnvVariable:
  - name: NORMAL_VAR
    value: "foobar"
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

Alternatively, the less messy but slightly less user-friendly option would be to allow the full use of the syntax with the `extraEnv` variable, this would likely be a breaking change unless someone can think up the logic to allow this kind of syntax:

```yaml
extraEnv:
  USE_AIKARS_FLAGS: "true"
  HOST_IP:
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
 ```
 
Thoughts?
