### ISSUE TITLE
Error setting extraEnv variables

### ISSUE THREAD

**Issue by cclloyd** [itzg/minecraft-server-charts#8]
I'm trying to set some env variables to use with the `multiarch` image of minecraft, but helm is spitting an error when trying to deploy.

    extraEnv:
      FTB_MODPACK_ID: "35"

Gives me the error 

>  v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 3, error found in #10 byte of ...|,"value":35}],"image|..., bigger context ...|TS","value":""},{"name":"FT
B_MODPACK_ID","value":35}],"image":"itzg/minecraft-server:multiarch","ima|...

Helm version: `version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`
Chart version: 2.0.2
App version: 1.14.4

**Comment by itzg** [comment]
@billimek do you have any ideas? Should there be quotes around the value of `value` here:

https://github.com/itzg/minecraft-server-charts/blob/19b131eed03f87153c19383b00f4115a7fad3b06/charts/minecraft/templates/deployment.yaml#L183

**Comment by billimek** [comment]
I believe that we should have quotes around this, yes.  Looking for a concrete example to compare with.

**Comment by billimek** [comment]
We could try something like this, instead:

```yaml
          {{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
          {{- end }}
```

**Comment by cclloyd** [comment]
I should also note that when I have it set to the following,

    extraEnv:
      FTB_MODPACK_ID:
        value: 35  # FTB Revelations

I get this error

> [init] Resolving type given FTBA
> jq: error (at <stdin>:0): Cannot iterate over null (null)
> [init] ERROR unable to resolve latest modpack version ID for modpack map[value:35]

**Comment by itzg** [comment]
> We could try something like this, instead:
> 
> 
> 
> ```yaml
> 
>           {{- with .Values.extraEnv }}
> 
> {{ toYaml . | indent 12 }}
> 
>           {{- end }}
> 
> ```

Ah yes, that’s what I have seen done before in this scenario.

**Comment by itzg** [comment]
As a side note, I should really add the new “FTB” variables as chart values.

**Comment by TJM** [comment]
I think, although I *hate* arrays of hashes, that the environment variables are not just a simple hash..

```
env:
  - name: ENV_VAR
    value: theValue
  - name: ANOTHER_VAR
    value: something else
```

... and I think the reason is that sometimes you want something more than a simple value, like:

```
              env:
              - name: PGUSER
                value: xray
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    key: postgresql-password
                    name: xray-postgresql
```
