### ISSUE TITLE
Backup container fails to start

### ISSUE THREAD

**Issue by cburza** [itzg/minecraft-server-charts#94]
When using mcbackup, the backup container fails to start with:

`level=fatal msg="Failed to run sub-command" error="fork/exec /usr/bin/backup: operation not permitted".`

My Helm values:
```
mcbackup:
  enabled: true
  persistence:
    annotations:
      nfs.io/storage-path: minecraft-backups
    storageClass: deimos-nfs

    backupDir:
      enabled: true
      Size: 5Gi
```

I checked and I have the following permissions set for the backups directory:
`drwxrwxrwx   1 1000 2000    6 Jan 12 05:55 backups`

I have not been able to get the backup container to run unless I make the runAsUser root:
```
securityContext:
    runAsUser: 0
 ```
Is there perhaps another way? Or should the Helm chart allow us to set the run as user as root?

I assume the issue is in entrypoint-demoter that tries to change the user which runs the backup command. 

`setCredentials(uid, gid, command)`
